### ISSUE TITLE
Confirm your email address

### ISSUE THREAD

**Issue by rmharp** [rospino74/Quizlet-Bypass#443]
### Browser Version

Chrome

### Exension Version

1.5.3

### Actual behaviour

Extension shows a screen which says "Confirm your email address." I've attached a screenshot. I've tried clearing my cookies and redownloading but neither fixed this issue.
![Screenshot 2023-10-27 at 10 06 42 PM](https://github.com/rospino74/Quizlet-Bypass/assets/122546380/75a33397-d18a-47b0-919b-d5d08fdb18c3)

**Comment by truongng201** [comment]
I have the same issue. How can i bypass that

**Comment by rospino74** [comment]
I published a [new release](https://github.com/rospino74/Quizlet-Bypass/releases/tag/v1.5.4) to address the issue. Please tell me if it has fixed the problem.

**Comment by rmharp** [comment]
Hmm sort of the confirm your email address is gone but the ability to scroll is gone. To be clear you're able to hit show more steps but unable to scroll down to see them past the first one or two steps.

**Comment by truongng201** [comment]
I have the same problem that I cannot scroll doơn. However still see the solution by zoom in or zoom out the screen. But still a little bit hard to use

**Comment by rospino74** [comment]
![immagine](https://github.com/rospino74/Quizlet-Bypass/assets/34315725/90db893b-bfe2-4744-b790-667f66f7198f)
I can still see the scroll bar, what is the URL of the page you are looking at? If you open the console do you see any element with the `overflow: hidden;` attribute?

**Comment by HeadlessChickenFajita** [comment]
Prefacing this by saying I've made an account just so I can reply to your comment. I am experiencing the same bug on the following URL

https://quizlet.com/explanations/textbook-solutions/calculus-early-transcendentals-9th-edition-9781337613927/chapter-11-exercises-2b-773a4a1b-7243-48e6-9d84-e35aa8085692

![image](https://github.com/rospino74/Quizlet-Bypass/assets/126847718/afa41bad-6394-42ad-9fdc-4fef5ae4e401)

**Comment by rospino74** [comment]
Does [this build](https://github.com/rospino74/Quizlet-Bypass/suites/17716222070/artifacts/1014209666) work?

**Comment by HeadlessChickenFajita** [comment]
> Does [this build](https://github.com/rospino74/Quizlet-Bypass/suites/17716361129/artifacts/1014218653) work?

This seems to fix the scrolling bug. Thank you!

**Comment by 2019vwsharan** [comment]
> Does [this build](https://github.com/rospino74/Quizlet-Bypass/suites/17716361129/artifacts/1014218653) work?

it still gives me the same notification to verify the email so I can not scroll at all

**Comment by rmharp** [comment]
Looks to be working on my end, thanks.
